version: '3.8'

services:

  mysql:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: niku # 设置 Mysql 用户名称
      MYSQL_PASSWORD: 123 # 设置 Mysql 用户密码
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/var/lib/mysql

  redis:
    image: redis
    environment:
      - TZ=Asia/Shanghai
    privileged: true
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - ./redis/data:/data
      # - ./redis/db:/var/lib/redis
      # - ./redis/log/redis-server.log:/var/log/redis/redis-server.log
    ports:
      - "6379:6379"
    command: "redis-server /etc/redis/redis.conf"
    restart: always
    container_name: redis