MySQL:
  Host: "127.0.0.1"
  Port: 3307
  User: "niku"
  Password: "123"
  DBName: "TikTokDB"
  CharSet: "utf8mb4"
  ParseTime: true
  loc: "Local"
  maxIdleConns: 10 # 空闲连接池中连接的最大数量
  maxOpenConns: 100 # 打开数据库连接的最大数量